config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :bookings, only: :create
  end
  get "/dashboard", to: 'dashboard#profil', as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :photos
  belongs_to :user

  CATEGORY = ['PANTACOURT', 'BERMUDA', 'PANTALON', 'JUPE', 'KILT', 'CHEMISE', 'T-SHIRT', 'ROBE', 'KIMONO', 'PEIGNOIR', 'PYJAMA', 'CHAUSSON', 'MULE', 'PANTOUFLE', 'VESTE', 'CAMISOLE', 'CARDIGAN', 'PARKA', 'SAC', 'SAC À MAIN', 'SAC À DOS', 'CAPE', 'CHAPEAU', 'GANT', 'BASKET']

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :category, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_article,
    against: [ :name, :description, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :articles, dependent: :destroy
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    if params[:query] && params[:query] != ""
      @articles = policy_scope(Article).search_by_article(params[:query])
    else
      @articles = policy_scope(Article).order(created_at: :desc)
    end
  end

  def show
    @article = Article.find(params[:id])
    authorize @article
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.create(article_params)
    @article.user = current_user
    @article.save
    authorize @article
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    authorize @article
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url notice: 'Article was successfully deleted.' }
    end
  end

  private

  def article_params
    params.require(:article).permit(:name, :description, :price, :category, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new
    @article = Article.find(params[:article_id])
    @booking.article = @article
    @booking.user = current_user
    @booking.save
    authorize @booking
    redirect_to dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def profil
    @articles = current_user.articles
    authorize @articles
    # @bookings = @articles.map(&:booking).select{|boo|!boo.nil?}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="container-list">
 <div class="grid-product">
  <% @articles.each do |article| %>
    <%= link_to article_path(article), class: 'card' do %>
        <% if article.photos.attached? %>
          <%= cl_image_tag article.photos.first.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="card__image" alt="" />
        <% end %>
      <div class="card__overlay">
        <div class="card__header">
          <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path /></svg>
          <div class="card__header-text">
            <h2><%= article.name %></h2>

          </div>
        </div>
        <p><%= article.category %> <strong><%= article.price %></strong> €.</p>
      </div>

    <% end %>
  <% end %>
 </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col-xs-12 col-sm-8 col-md-6">
        <h1>Vendre un nouvel article</h1>
      <div class="form-container">
        <div class="form-new">
          <%= simple_form_for @article do |f| %>
          <div class="col-12">
            <%= f.input :name, label: "Nom de l'article", placeholder: 'Veste en cuir' %>
          </div>
          <div class="col-12">
            <%= f.input :description, label: "Description", placeholder: "Neuve, n'a jamais servie" %>
          </div>
          <div class="col-3">
            <%= f.input :price, label: "Prix", placeholder: "15" %>
          </div>
          <div class="col-6">
            <%= f.input :category, label: "Catégorie", placeholder: "VESTE", collection: Article::CATEGORY %>
          </div>
          <div class="col-12">
            <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Photo(s)", placeholder: "Sélectionner" %>
          </div>
          <div class="col-12">
            <%= f.button :submit, "CREER", class: "btn btn-flat" %>
          </div>
          <% end %>
        </div>
      </div>
        <%= link_to "Retour à la page d'accueil", root_path, class: "btn btn-gradient" %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<%# Grande div qui enveloppe carousel + description : %>
<div class="container-show">

  <div class="card-show">
    <%# Carousel photos %>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="d-block">
            <% if @article.photos.attached? %>
              <%= cl_image_tag @article.photos.first.key, height: 300, width: 500, crop: :fill %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1509067917181-3ec8d8ef5170?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGRyZXNzaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="Pas de photos pour cet article" />
            <% end %>
          </div>
        </div>
        <div class="carousel-item">
          <div class="d-block">
            <% if @article.photos.attached? && @article.photos.second %>
              <%= cl_image_tag @article.photos.second.key, height: 300, width: 500, crop: :fill %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1509067917181-3ec8d8ef5170?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGRyZXNzaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="Pas de photos pour cet article" />
            <% end %>
          </div>
        </div>
        <div class="carousel-item">
          <div class="d-block">
            <% if @article.photos.attached? && @article.photos.second %>
              <%= cl_image_tag @article.photos.third.key, height: 300, width: 500, crop: :fill %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1509067917181-3ec8d8ef5170?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGRyZXNzaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="Pas de photos pour cet article" />
            <% end %>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </button>
    </div>
    <%# Fin de Carousel photos %>
    <%# Description et prix de l'article ci-dessous : %>
    <div class="card-details-show">
      <div class="category-show">
        <h1><%= @article.category %></h1>
      </div>
      <div class="article-name-show">
        <h2> <%= @article.name %></h2>
      </div>
      <div class="description-show">
        <p><%= @article.description %></p>
      </div>
      <div class="prix-show">
        <p>
          <strong>Prix:</strong>
          <%= @article.price %> €
        </p>
      </div>
    </div>
    <%#  fin Description et prix de l'article ci-dessous : %>
  </div>
  <div class="card-link-show">
    <%= link_to 'Retour à la liste des articles', articles_path(@articles), class: "btn btn-gradient" %>
    <% unless current_user.id == @article.user_id %>
      <%= link_to 'Réserver cet article', article_bookings_path(@article), method: :post, class: "btn btn-gradient" %>
    <% end %>
    <% if policy(@article).destroy? %>
     <%= link_to 'Supprimer cet article', article_path(@article), class: "btn btn-gradient",
          method: :delete,
          data: { confirm: "êtes vous sûr(e) de vouloir supprimer cet article?" } %>
    <% end %>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>
<% redirect_to dashboard_path %>

app/views/dashboard/profil.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Mon dressing</a>
    <a class="nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Mes réservations</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="container-list">
      <div class="grid-product">
        <% @articles.each do |article| %>
          <%= link_to article_path(article), class: 'card' do %>
              <% if article.photos.attached? %>
                <%= cl_image_tag article.photos.first.key, height: 300, width: 400, crop: :fill %>
              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="card__image" alt="" />
              <% end %>
            <div class="card__overlay">
              <div class="card__header">
                <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path /></svg>
                <div class="card__header-text">
                  <h2><%= article.name %></h2>
                </div>
              </div>
              <p><%= article.category %> <strong><%= article.price %></strong> €.</p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
    <div class="container-list">
      <div class="grid-product">
        <% current_user.bookings.map(&:article).each do |article| %>
          <%= link_to article_path(article), class: 'card' do %>
              <% if article.photos.attached? %>
                <%= cl_image_tag article.photos.first.key, height: 300, width: 400, crop: :fill %>
              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="card__image" alt="" />
              <% end %>
            <div class="card__overlay">
              <div class="card__header">
                <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path /></svg>
                <div class="card__header-text">
                  <h2><%= article.name %></h2>
                </div>
              </div>
              <p><%= article.category %> <strong><%= article.price %></strong> €.</p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sock Away</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "components/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# Banner ci-dessous (avec carousel) :  %>

<div class="banner">
  <div class="banner-text">
    <h1>SOCK AWAY - <strong>Dénichez</strong> des <strong>pépites</strong>! ✨</h1>
    <p>Parcourez notre catalogue et trouvez le meilleur de la seconde main et du vintage en ligne.</p>
    <%= link_to "COMMENCEZ À CHINER", articles_path, class: "btn btn-flat" %>
  </div>
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.unsplash.com/photo-1540221652346-e5dd6b50f3e7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1769&q=80" class="d-block" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1520006403909-838d6b92c22e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" class="d-block" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1619161519929-befcb28d6384?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1774&q=80" class="d-block" alt="...">
      </div>
    </div>
  </div>
</div>

<%# fin de la banner  %>